<a href="https://colab.research.google.com/github/TienNguyen0712/data-science-foundations/blob/main/math_statistic/linear_algebra/linear_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 📐 **Đại số tuyến tính**

## **1. Các khái niệm cơ bản**

### **1.1. Scalars (Số vô hướng)**

**Định nghĩa**

Là một số đơn lẻ, không có hướng, chỉ có độ lớn

**Ví dụ**

$$3, -5, 0.1, π$$

Nếu x = 4 và a = 3 thì:

$$a . x = 12$$

**Lưu ý**

Scalar thường nhân với vector hoặc ma trận để co giãn chúng

### **1.2. Vector**

**Định nghĩa**

Là một danh sách có thứ tự các scalar, biểu diễn độ lớn + hướng

Vecto có thể là mũi tên trong không gian, mỗi điểm dữ liệu, trạng thái của hệ thống

**Ví dụ vector trong học máy**

$$\mathbf{Chiều cao, cân nặng, tuổi} =
\begin{bmatrix}
170\\
65\\
21\\
\end{bmatrix}
$$

**Ký hiệu cho vecto**

- **Vecto cột**
$$\mathbf{v} =
\begin{bmatrix}
v_1\\
v_2\\
\vdots\\
v_n
\end{bmatrix}
$$

- **Vecto hàng**


$$\mathbf{v}^⊤ =
\begin{bmatrix}
v_1, v_2, …, v_n
\end{bmatrix}
$$

- **Vecto trong không gian n**

$$\mathbf{v} \in \mathbb{R}^n
$$

- **Vector cơ sở**

$$\mathbf{e}_1 =
\begin{bmatrix}
1\\0\\0
\end{bmatrix}
$$

- **Chuản độ dài của vector**

$$\|\mathbf{v}\|$$

- **Tích vô hướng**

$$\mathbf{u}^\top \mathbf{v},
 \quad \langle \mathbf{u}, \mathbf{v} \rangle
$$

**Ví dụ về vecto**

$$\mathbf{v} =
\begin{bmatrix}
2\\
-1\\
3\\
\end{bmatrix}
$$


In [ ]:
Chieucao, Cannang, Tuoi = 170, 65, 21 # Xem như tạo một vector lưu các giá trị lần lượt chiều cao, cân nặng, tuổi

### **1.3. Ma trận**

**Định nghĩa**

Là một bằng chữ nhật các scalar, sắp xếp theo hàng và cột

Ngoài ra có thể tạo ma trận từ nhiều vecto xếp chồng, một phép biến đổi tuyến tính

Theo biểu thức như:

$$y = Ax$$

Mô tả ma trận biến đổi vector đầu vào thành vector đầu ra

$$\mathbf{A} =
\begin{bmatrix}
1 & 0\\
0 & 2\\
\end{bmatrix} \quad,
\mathbf{x} =
\begin{bmatrix}
3\\
4\\
\end{bmatrix}
$$

$$\mathbf{Ax} =
\begin{bmatrix}
3\\
8\\
\end{bmatrix}$$

**Ký hiệu cho ma trận**

- **Kích thước m x n**

$$\mathbf{A} \in \mathbb{R}^{m \times n}$$

- **Dạng tổng quát của ma trận**

$$\mathbf{A} =
\begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n}\\
a_{21} & a_{22} & \cdots & a_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
a_{m1} & a_{m2} & \cdots & a_{mn}
\end{bmatrix}$$

- **Ma trận vuông**

$$\mathbf{A} \in \mathbb{R}^{n \times n}$$

- **Ma trận đơn vị**

$$\mathbf{I}_n =
\begin{bmatrix}
1 & 0 & \cdots & 0\\
0 & 1 & \cdots & 0\\
\vdots & \vdots & \ddots & \vdots\\
0 & 0 & \cdots & 1
\end{bmatrix}$$

- **Ma trận chuyển vị**

$$\mathbf{A}^\top$$

- **Ma trận đường chèo**

$$\mathbf{I}_n =
\begin{bmatrix}
λ_1 & 0 & \cdots & 0\\
0 & λ_2 & \cdots & 0\\
\vdots & \vdots & \ddots & \vdots\\
0 & 0 & \cdots & λ_n
\end{bmatrix}$$

**Ví dụ**

$$\mathbf{A} =
\begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6
\end{bmatrix}
$$

Ma trận trên thuộc không gian 2 x 2

**Trong dữ liệu**

Ma trận có thể được biểu diễn với **Mỗi hàng là một mẫu dữ liệu** và **Mội cột là một đặc trưng**

$$\mathbf{A} =
\begin{bmatrix}
170 & 65 & 21\\
160 & 55 & 19
\end{bmatrix}
$$


In [5]:
import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 6],    # Biểu diễn ma trận bằng numpy
    [7, 8, 9]
])

A.shape # Kích thước ma trận

(3, 3)

### **1.4. Tensors**

**Định nghĩa**

Là khái quát của:
- scalar (bậc 0)
- vector (bậc 1)
- ma trận (bậc 2)
- tensor bậc cao (bậc >= 3)

Là mảng nhiều chiều:
- Ảnh xám: H X W
- Ảnh màu: H X W x 3
- Video: T X H X W x 3

**Ví dụ**

Giả sử ta có 2 ma trận 2 x 2

$$\mathcal{T}
=
\left[
\begin{bmatrix}
1 & 2\\
3 & 4
\end{bmatrix},
\begin{bmatrix}
5 & 6\\
7 & 8
\end{bmatrix}
\right]
$$

Kích thước sẽ là: **2 x 2 x 2**

**Tensor trong học máy và học sâu**
- Input cho CNN
- Batch dữ liệu
- Trọng số mang neural

### **1.5. Các định nghĩa khác**

**Độc lập tuyến tính**

Các vector độc lập tuyến tính nếu không vector nào được viết được bằng vcasc vector còn lại

**Cơ sở**

Một tập vector là cơ sở của V nếu:
- Sỉnh ra v
- Độc lập tuyến tính

**Ví dụ**

Cơ sở chuẩn cảu R^3


$$\mathbf{e_1} =
\begin{bmatrix}
1\\
0\\
0\\
\end{bmatrix}, \quad
\mathbf{e_2} =
\begin{bmatrix}
0\\
1\\
0\\
\end{bmatrix}, \quad
\mathbf{e_3} =
\begin{bmatrix}
0\\
0\\
1\\
\end{bmatrix}
$$


**Số chiều**

$$dim(V)$$

Số chiều của không gian vector = số vector trong 1 cơ sở

Mọi sơ sở của cùng một không gian vector đều có cùng số phân tử



## **2. Các phép toán**

### **2.1. Cộng và trừ**

Hai ma trận cộng/trừ được khi cùng kích thước phép toán thực hiện trên từng phâng tử

**Ví dụ**

$$
\mathbf{u} =
\begin{bmatrix}
1\\
2\\
3
\end{bmatrix},
\quad
\mathbf{v} =
\begin{bmatrix}
4\\
-1\\
2
\end{bmatrix}
$$

- **Cộng vector**

$$\mathbf{u} + \mathbf{v}
=
\begin{bmatrix}
1+4\\
2+(-1)\\
3+2
\end{bmatrix}
=
\begin{bmatrix}
5\\
1\\
5
\end{bmatrix}
$$

- **Trừ vector**

$$
\mathbf{u} - \mathbf{v}
=
\begin{bmatrix}
1-4\\
2-(-1)\\
3-2
\end{bmatrix}
=
\begin{bmatrix}
-3\\
3\\
1
\end{bmatrix}
$$


In [10]:
import numpy as np

A = np.array([
    [1, 2, 3]
])

B = np.array([
    [4, -1, 2]
])

A.shape # Kích thước ma trận
B.shape # Kích thước ma trận

C = A + B # Cộng ma trận

D = A - B # Trừ ma trận

In [11]:
C

array([[5, 1, 5]])

In [12]:
D

array([[-3,  3,  1]])

### **2.2. Nhân**

**Nhân ma trận với số vô hướng**

$$
2\mathbf{u}
=
2
\begin{bmatrix}
1\\
2\\
3
\end{bmatrix}
=
\begin{bmatrix}
2\\
4\\
6
\end{bmatrix}
$$

**Nhân ma trận với vector**

Nếu:
- A là ma trận m x n
- x là vector n x 1

⇒ Ax xác định và cho ra vector m x 1

**Ví dụ**

$$
A =
\begin{bmatrix}
1 & 2\\
3 & 4
\end{bmatrix},
\quad
\mathbf{x} =
\begin{bmatrix}
1\\
-1
\end{bmatrix}
$$

$$
A\mathbf{x}
=
\begin{bmatrix}
1\cdot1 + 2\cdot(-1)\\
3\cdot1 + 4\cdot(-1)
\end{bmatrix}
=
\begin{bmatrix}
-1\\
-1
\end{bmatrix}
$$

**Nhân ma trận với ma trận**

Nếu:
- A là m x n
- B là n x p

⇒ AB là m x p

$$
A =
\begin{bmatrix}
1 & 2\\
3 & 4
\end{bmatrix},
\quad
B =
\begin{bmatrix}
2 & 0\\
1 & 1
\end{bmatrix}
$$

$$
AB =
\begin{bmatrix}
1\cdot2 + 2\cdot1 & 1\cdot0 + 2\cdot1\\
3\cdot2 + 4\cdot1 & 3\cdot0 + 4\cdot1
\end{bmatrix}
=
\begin{bmatrix}
4 & 2\\
10 & 4
\end{bmatrix}
$$

In [14]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]]) # Tạo ma trận A

B = np.array([[2, 0],
              [1, 1]])  # Tạo ma trận B

x = np.array([1, -1]) # Tạo vector x

u2 = 2 * u # Nhân số vô hướng với ma trận
AB = A @ B # Nhân ma trận với ma trận
Ax = A @ x # Nhân ma trận với vector


In [15]:
u2, AB, Ax

(array([[2],
        [4],
        [6]]),
 array([[ 4,  2],
        [10,  4]]),
 array([-1, -1]))

### **2.3. Hệ phương trình tuyến tính**

**Dạng tổng quát**

$$
A\mathbf{x} = \mathbf{b}
$$

**Ví dụ về hệ phương trình**

$$
\begin{cases}
x + y = 3\\
2x - y = 0
\end{cases}
$$

**Dạng ma trận**

$$
\begin{bmatrix}
1 & 1\\
2 & -1
\end{bmatrix}
\begin{bmatrix}
x\\
y
\end{bmatrix}
=
\begin{bmatrix}
3\\
0
\end{bmatrix}
$$

**Nghiệm**

$$
\mathbf{x} =
\begin{bmatrix}
1\\
2
\end{bmatrix}
$$

**Giải bằng phương pháp khử Gauss**

Giải hệ:

$$
\begin{cases}
x+y=3\\
2x-y=0
\end{cases}
$$

**B1: Lập ma trận mở rộng**

$$
\left[
\begin{array}{cc|c}
1&1&3\\
2&-1&0
\end{array}
\right]
$$

**B2: Khử phần tử dưới (ở cột 1)**

$$
R_2 \leftarrow R_2 - 2R_1
$$

Tính từng phần tử:
- Cột 1: 2 - 2 . 1 = 0
- Cột 2: -1 - 2 . 1 = -3
- Vế phải: 0 - 2 . 3 = -6

Kết quả

$$
\left[
\begin{array}{cc|c}
1&1&3\\
0&-3&-6
\end{array}
\right]
$$

**B3: Chuẩn hóa hàng 2 (đưa hệ số về 1)**

$$
R_2 \leftarrow \frac{-1}{3}R_2
$$

$$
\left[
\begin{array}{cc|c}
1&1&3\\
0&1&2
\end{array}
\right]
$$

**B4: Khử phía trên cột 2 (đưa về dạng bậc thang rút gọn)**

$$
R_1 \leftarrow R_1 - R_2
$$

- Cột 2: 1 - 1  = 0
- Vế phải: 3 - 2 = 1

$$
\left[
\begin{array}{cc|c}
1&0&1\\
0&1&2
\end{array}
\right]
$$

Kết luận

$$
x=1,\quad y=2
$$




In [27]:
A = np.array([[1., 1., 3.],
              [2., -1., 0.]])  # ma trận mở rộng

A[1] = A[1] - 2 * A[0]

A[1] = A[1] / (-3)

A[0] = A[0] - A[1]

In [28]:
A

array([[ 1.,  0.,  1.],
       [-0.,  1.,  2.]])

### **2.4. Ma trận dặc biệt**

**Ma trận chuyển vị**

Ma trận chuyển vị A^T được tạo bằng cách đỏi hàng thành cột

$$
A =
\begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6
\end{bmatrix}
\Rightarrow
A^T =
\begin{bmatrix}
1 & 4\\
2 & 5\\
3 & 6
\end{bmatrix}
$$

$$
(AB)^T = B^T A^T
$$

In [17]:
A.T

array([[1, 3],
       [2, 4]])

**Ma trận bậc thang**

Một ma trận thỏa tất cả các điều kiện sau:
- Các hàng khác 0 nằm trên các hàng toàn 0
- Phần tử khác 0 đầu tiên của mỗi hàng (gọi là pivot) nằm bên phải pivot của hàng phía trên
- Các phần tử dưới mỗi pivot đều bằng 0

**Minh họa**

$$
\begin{bmatrix}
\ast & \ast & \ast & \ast\\
0 & \ast & \ast & \ast\\
0 & 0 & \ast & \ast\\
0 & 0 & 0 & 0
\end{bmatrix}
$$

*: là số bất kỳ có thể bằng 0 hoặc khác 0

$$
\begin{bmatrix}
1&2&-1\\
0&3&4\\
0&0&5
\end{bmatrix}
$$

Pivot:
- Pivot hàng 1: cột 1
- Pivot hàng 2: Cột 2
- Pivot hàng 3: cột 3
- Mọt phần tử dwosi pivot đề bằng 0

In [30]:
C = np.array([[ 1.,  1.,  1.,  3.],
       [ 0.,  1., -1.,  1.],
       [ 0.,  0., -1.,  1.]])

C

array([[ 1.,  1.,  1.,  3.],
       [ 0.,  1., -1.,  1.],
       [ 0.,  0., -1.,  1.]])

**Ma trận đơn vị**

Ma trận đơn vị bậc n ký hiệu
$$
I_n
$$
đường chéo chính toàn 1, còn lại 0

**Minh họa**

$$
I_n =
\begin{bmatrix}
1 & 0 & \cdots & 0\\
0 & 1 & \cdots & 0\\
\vdots & \vdots & \ddots & \vdots\\
0 & 0 & \cdots & 1
\end{bmatrix}
$$

**Tính chất**

$$
AI_n = I_nA = A
$$

**Ví dụ**

$$
I_3=
\begin{bmatrix}
1&0&0\\
0&1&0\\
0&0&1
\end{bmatrix}
$$

Ma trận đơn vị bậc 3

In [18]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Ma trận chéo**

Ma trận chéo có dạng (ngoài đường chéo chính đều bằng 0)

**Minh họa**

$$
D=
\begin{bmatrix}
d_1&0&\cdots&0\\
0&d_2&\cdots&0\\
\vdots&\vdots&\ddots&\vdots\\
0&0&\cdots&d_n
\end{bmatrix}
$$

**Tính chất**
- Nhân với vector: Dx chỉ là "phóng to/thu nhỏ" từng tọa độ
- Nếu di khác 0 với mọi i thì D khả nghịch


In [19]:
D = np.diag([2, 3, 5])
D

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

**Ma trận đối xứng**

Đối xứng khi ma trận bằng với ma trận chuyển vị của nó

$$
A \text{ đối xứng } \Longleftrightarrow A^T = A
$$

**Ví dụ**

$$
A=
\begin{bmatrix}
2&-1&0\\
-1&3&4\\
0&4&1
\end{bmatrix}
\quad\Rightarrow\quad A^T=A
$$

In [22]:
S = np.array([[2, -1, 0],
              [-1, 3, 4],
              [0, 4, 1]])

np.allclose(S, S.T) # Kiểm tra tính đối xứng

True

**Ma trận nghịch đảo**

Với ma trận vuông A, nếu tồn tại
$$ A^-1 $$ sao cho
$$
AA^{-1}=A^{-1}A=I
$$

thì A gọi laf khả nghịch.
- A khả nghịch khi det(A) khác 0
- Trong thực hành hay kiểm tra bằng tính khử Gauss nếu rút gọn được về I thì khả nghịch

**Ví dụ**

$$
A=
\begin{bmatrix}
a&b\\
c&d
\end{bmatrix}
\quad\text{và}\quad ad-bc\neq 0
$$

thì

$$
A^{-1}=\frac{1}{ad-bc}
\begin{bmatrix}
d&-b\\
-c&a
\end{bmatrix}
$$

In [24]:
A = np.array([[1, 2],
              [3, 4]])

A_inv = np.linalg.inv(A)

A @ A_inv


array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

## **3. Hạng ma trận**

## **4. Vecto riêng & Giá trị riêng**

## **4. SVD (Phân rã ma trận)**

## **5. Giảm chiều ma trận (PCA)**

- Không gian con
- Không gian cột, dòng, null
- Hình học của phép biens đôi tuyến tính
- Phép chiếu

## **6. Chuẩn & tối ưu hóa tuyến tính**

- CHuẩn vecto & ma trận
- Khoảng cách
- Bài toán least squares
- Regularization
  - L2, L1